[env]
TERM = "xterm-256color"

[font]
size = 16.0

[terminal.shell]
args = ["-c", "~/.asdf/shims/zellij -l compact"]
program = "/bin/zsh"

[window]
dynamic_title = false
opacity = 0.75
startup_mode = "Maximized"
