[env]
TERM = "xterm-256color"

[font]
size = 16.0
builtin_box_drawing = true

[terminal.shell]
args = ["-c", "tmux attach || tmux new-session"]
program = "/bin/zsh"

[window]
#dynamic_title = false
opacity = 0.75
startup_mode = "Maximized"

[window.padding]
x = 2
y = 2

